Project structure
paratskiy-organization/neighbor_helper pull request #15
Opened 2020-11-20 15:17 UTC by GorgeousPuree

Слияние базовой структуры проекта в ветку `develop`.

2020-11-20 15:55 UTC, paratskiy requested changes

2020-11-20 15:55 UTC, paratskiy commented on .idea/dictionaries/dashaonishchenko.xml
> +</component>
Нужно удалить и гитигнор

2020-11-20 15:55 UTC, paratskiy commented on src/configs/sequelize.config.js
> +        "host": "127.0.0.1",
DATABASE_HOST

2020-11-20 15:55 UTC, paratskiy commented on src/database/migrations/20201116212205-change-enum-assignment.js
> +      newValues: ['Not done', 'Done'],
Not_done

2020-11-20 15:55 UTC, paratskiy commented on src/helpers/ServiceResponse/index.js
> +        this.message = message || this.message;
this.message = message || message

2020-11-20 15:55 UTC, paratskiy commented on src/helpers/ServiceResponse/index.js
> +        this.model = model || this.model;
this.model = model || model

2020-11-20 15:55 UTC, paratskiy commented on src/services/user.service.js
> +}
потом нужно будет добавить проверки

2020-11-20 16:06 UTC, GorgeousPuree commented on src/services/user.service.js
> +}
Вообще это был пример-заглушка сервиса. Закомментил его.

2020-11-20 16:52 UTC, paratskiy approved these changes

2020-11-21 10:43 UTC, paratskiy approved these changes

2020-11-21 11:56 UTC, Dashawvr approved these changes

2020-11-21 11:58 UTC, merged