Project settings
paratskiy-organization/neighbor_helper pull request #2
Opened 2020-11-13 12:55 UTC by GorgeousPuree

`.idea` folder was removed;
eslint was initialized with `airbnb-base` package;

2020-11-13 21:29 UTC, paratskiy approved these changes

2020-11-15 18:22 UTC, maksim-luzin commented
The general council approved. I agree.

2020-11-15 20:37 UTC, maksim-luzin commented
Reopen pull request.

2020-11-16 17:34 UTC, paratskiy approved these changes

2020-11-16 20:01 UTC, maksim-luzin requested changes
Ok merge

2020-11-16 20:13 UTC, maksim-luzin approved these changes

2020-11-16 20:13 UTC, merged

2020-11-16 20:14 UTC, paratskiy approved these changes