Location service
paratskiy-organization/neighbor_helper pull request #21
Opened 2020-11-22 21:59 UTC by GorgeousPuree

Базовая имплементация `location `service в `src/services/location.service.js`.

2020-11-22 23:02 UTC, maksim-luzin requested changes
The create method to should return the id on success.
The getAllByTelegramId method can be used as an extension of the user model. Make a subquery of all locations on it.

2020-11-22 23:23 UTC, GorgeousPuree commented
> The create method to should return the id on success.
> The getAllByTelegramId method can be used as an extension of the user model. Make a subquery of all locations on it.

Зачем нужен айди юзера после создания?
По поводу второго, предлагаешь вытянуть все локации из самого юзера, а не из Location по телеграм айди? Разве есть разница?

2020-11-23 12:38 UTC, maksim-luzin commented
According to the diagram, when creating an assignment, there is a button to add a location.  We use the location id as a link for the assignment on location.

2020-11-23 12:45 UTC, maksim-luzin commented
If you remove the option to create a location when creating an ad, then the id is not needed.

2020-11-23 13:37 UTC, GorgeousPuree commented
> According to the diagram, when creating an assignment, there is a button to add a location. We use the location id as a link for the assignment on location.

Да, там есть эта кнопка. При нажатии пользователь создаёт новую локацию. Это равно тому, как если бы пользователь нажал "Добавить локацию" в главном меню. Но только находясь в создании/поиске объявления после добавления новой локации, пользователю опять выпадет список со всеми его локациями вместе с только что добавленной. Получается, если мы хотим получать айди локации сразу после добавления, то надо и запрашивать айдишники для всех остальных локаций в списке, чтобы все было целостно.
Стоит сказать, что если так делать, то айди локации будет возвращаться и после создания через главное меню, когда он не нужен.
Айди локации будем получать передавая telegramId и уникальный localName. А дальше он будет использоваться, либо для создания объявления, либо для поиска.

Кратко: я не вижу смысла в возврате айди локации после создания, потому что это поменяет логику.

2020-11-23 15:00 UTC, paratskiy approved these changes

2020-11-23 22:54 UTC, maksim-luzin approved these changes
Good. Do as you understand.

2020-11-24 08:57 UTC, merged