Add hanlers
paratskiy-organization/neighbor_helper pull request #26
Opened 2020-11-26 23:01 UTC by maksim-luzin

2020-11-27 00:26 UTC, GorgeousPuree requested changes

2020-11-27 00:26 UTC, GorgeousPuree commented on src/features/textHandler.js
> +      return menuMain(request);
Я не особо понимаю, зачем нужна прослойка с `menuMain` (лучше `mainMenu`), почему не писать прямо тут?

2020-11-27 08:17 UTC, maksim-luzin commented on src/features/index.js
> +    if (message.data) {
Для инлайн кнопок поправил. Для локации location приходит в message. Последний if считаю не нужным так как если не поймал не тот не тот то будет всё равно работать третий.

2020-11-27 08:18 UTC, maksim-luzin commented on src/features/textHandler.js
> +  BUTTON_ADD_LOCATION_MENU_ADD_LOCATION_HOME,
Кнопки убрал.

2020-11-27 08:21 UTC, maksim-luzin commented on src/features/textHandler.js
> +      return menuMain(request);
Это слой так называемой бизнес логики т. е. в ней мы отрабатывает нажатие кнопки. В textHandlere просто ловим его.

2020-11-27 08:21 UTC, maksim-luzin commented on src/controllers/menuMain.js
> +const { UserService } = require('../services');
Сервис поправил.

2020-11-27 09:16 UTC, paratskiy requested changes

2020-11-27 09:16 UTC, paratskiy commented on src/templates/mainMenu/mainMenu.js
> +const mainMenuMessage = (message) => {
mainMenuMessage = greeting || greetingMessage

2020-11-27 10:19 UTC, GorgeousPuree commented on src/features/index.js
> +    if (message.data) {
А если придёт стикер/аудио/видео? Оно же в текст хендлер попадёт.

2020-11-27 12:21 UTC, maksim-luzin commented on src/controllers/menuMain.js
> +module.exports = menuMain;
В menuMain уже используется переменная mainMenu как шаблон меню.

2020-11-27 12:23 UTC, maksim-luzin commented on src/templates/mainMenu/mainMenu.js
> +  if (message.text === COMMAND_START || message.text === BUTTON_MAIN_MENU_ABOUT_US) {
Это для вывода двух разных сообщений. Или 'О нас' или 'Меню'.

2020-11-27 13:01 UTC, GorgeousPuree commented on src/features/index.js
> +    if (message.data) {
Эксепшн всё равно выпадет. `message` может не прийти в `originalRequest`. Надо проверять сначала пришёл ли `message`. И ифы всегда нужны, потому что есть стикеры, аудио видео и тд.

2020-11-27 13:02 UTC, maksim-luzin commented on src/constants/button.text.js
> +exports.BUTTON_ALL_MENU_CANCEL = 'Отмена';
Я тоже так вначале думал. Но так видно сразу к чему эта кнопка.

2020-11-27 13:03 UTC, paratskiy commented on src/templates/mainMenu/mainMenu.js
> +  if (message.text === COMMAND_START || message.text === BUTTON_MAIN_MENU_ABOUT_US) {
В этом нет смысла, у нас будет одно главное меню и для "О нас" и для "Главная"

2020-11-27 13:06 UTC, paratskiy commented on src/controllers/menuMain.js
> +module.exports = menuMain;
Значит или здесь или в шаблонах не правильное название и оно не отображает сути
Нужно переименовывать

2020-11-27 13:09 UTC, paratskiy commented on src/constants/button.text.js
> +exports.BUTTON_ALL_MENU_CANCEL = 'Отмена';
я не согласен, это только путает

2020-11-27 13:10 UTC, paratskiy commented
Созвонимся и все обсудим

2020-11-27 13:16 UTC, maksim-luzin commented on src/constants/comand.js
> +exports.COMMAND_START = '/start';
Может быть, но так сразу понятно что это. Если через время открыть код, то у многих будет вопрс. Что это '/start'? А так сразу видно - команда.

2020-11-27 13:19 UTC, maksim-luzin commented on src/controllers/menuMain.js
> +
Этот контроллер  обрабатывает логику вывода меню и сообщений. Модульная система затем и нужна чтоб не писать весь код в 'кашу' в одном файле.

2020-11-27 13:31 UTC, paratskiy commented on src/controllers/menuMain.js
> +
Мы не пишем кашу в одном файле, контроллеры нужно применять там где это уместно.
Я написал, мы можем сделать и через контроллеры, но проверка лишняя, на созвоне поговорим

2020-11-27 13:39 UTC, paratskiy commented on src/constants/comand.js
> +exports.COMMAND_START = '/start';
Если у кого-то появиться вопрос что такое /start, у него также появиться вопрос что такое COMMAND_START
Как и с контроллерами, в константы нужно выносить только то что уместно, а не все подряд

2020-11-27 17:06 UTC, maksim-luzin commented on src/features/index.js
> +    if (message.data) {
Насколько я понимаю поле message приходит и с inline клавиатурой то-же, возможно и другими объектами. За чем его сразу смотреть?

2020-11-28 17:13 UTC, GorgeousPuree commented on src/configs/global.config.js
> +  BOT_TOKEN: process.env.BOT_TOKEN, // for local development
А зачем ты тут переименовал? Так ведь понятно, что это токен именно для телеграма.

2020-11-28 17:44 UTC, GorgeousPuree requested changes
В принципе я согласен, кроме 3 моментов:

1. Я против переименования `TELEGRAM_TOKEN` в `global.config.js` в `BOT_TOKEN`, потому что так непонятно, какой платформе принадлежит этот токен.
2. Я думаю, что темплейты типа `aboutUsTemplate` должны находится в их родительском темплейте, не стоит создавать для каждого маленького темплейта отдельную поддиректорию. То есть код из `aboutUsTemplate.js` должен перенестись в `mainMenuTemplate.js`.
3. Я считаю, что в `textHandler.js` на дефолт надо возвращать `mainMenuAction`. То есть при вводе неизвестной команды или при вызове неимплементированного функционала будет возвращаться главное меню. А `defaultMessageTemplate.js` переименовать в `errorMessageTemplate.js`, который будет возвращать "Ой, что-то пошло не так." И вот он будет отправляться в случае, если произошла ошибка в работе сервиса.

А также надо удалить `src/features/text.js`, так как он не используется.
И в `src/bot.js` явно указать платформы: `module.exports = botBuilder(messageHandler, { platforms: ['telegram'] });`

2020-11-28 17:44 UTC, GorgeousPuree commented on local.js
> +  throw new Error("Cann't find TEST_BOT_TOKEN in your environments");
'Could not find `TELEGRAM_TOKEN` / `BOT_TOKEN` in your environments'. В зависимости от того, что будет в `global.config.js`. Читай в общем выводе.

2020-11-28 17:44 UTC, GorgeousPuree commented on src/templates/defaultMessageTemplate/defaultMessageTemplate.js
> +const defaultMessageTemplate = 'Ой что то пошло не так.';
По поводу `errorMessageTemplate` написал в общем выводе, но само значение должно быть таким: 'Ой, что-то пошло не так.'

2020-11-28 17:44 UTC, GorgeousPuree commented on src/actions/mainActions.js
> +  const messageStart = `Здравствуй ${message.from.first_name}\n ${aboutUsTemplate}`;
'Здравствуй, ...'
Запятая.

2020-11-28 18:05 UTC, maksim-luzin commented on src/configs/global.config.js
> +  BOT_TOKEN: process.env.BOT_TOKEN, // for local development
Так у Павла в примере.

2020-11-28 18:20 UTC, maksim-luzin commented on local.js
> +  throw new Error("Cann't find TEST_BOT_TOKEN in your environments");
1.Сейас оправлю но так у Павла в примере и так как вы почти всё подчистую срисуете с него то и сделал как у него.
2. Насчёт шаблонов сделал как обговаривали вчера. 
3 Название вчера всем нравилось поэтому переделывать считаю не нужным. При неизвестной команде сделано как описано выводится сообщение "Что то пошло не так" и главное меню.
4.В src/bot.js я вообще ничего не делал и за эту задачу не брался. Допишу немного позже. Когда буду добавлять функционал на отправку в lambdqa-function.
В общем совершенству нет пределов.

2020-11-28 18:21 UTC, maksim-luzin commented on src/templates/defaultMessageTemplate/defaultMessageTemplate.js
> +const defaultMessageTemplate = 'Ой что то пошло не так.';
Согласен сейчас подправлю.

2020-11-28 18:21 UTC, maksim-luzin commented on src/actions/mainActions.js
> +  const messageStart = `Здравствуй ${message.from.first_name}\n ${aboutUsTemplate}`;
Согласен подправлю.

2020-11-28 18:51 UTC, GorgeousPuree commented on local.js
> +  throw new Error("Cann't find TEST_BOT_TOKEN in your environments");
Срисовываем всё, да не всё. В любом случае `TEST_BOT_TOKEN`, о котором говорится в эксепшене, вообще нет. Есть либо `BOT_TOKEN`, который ты переименовал, либо оригинальный `TELEGRAM_TOKEN`.
В `src/bot.js` там просто одну строчку дописать, и этот пулл реквест скоро аппрувать будем, поэтому я попросил сделать это сейчас.

2020-11-28 20:10 UTC, GorgeousPuree approved these changes

2020-11-29 02:14 UTC, GorgeousPuree requested changes

2020-11-29 02:14 UTC, GorgeousPuree commented on src/templates/aboutUsTemplate.js/aboutUsTemplate.js
> +const aboutUsTemplate = 'Я бот для организации взаимопомощи соседей.';
Давайте выносить темплейты текста как и кнопки. Надо создать `message.text.js` как и `button.text.js` и туда записывать темплейты отправляемого текста.

2020-11-29 02:14 UTC, GorgeousPuree commented on src/templates/mainMenuTemplate/mainMenuTemplate.js
> +];
Предлагаю именовать темплейты кнопок с припиской _Keyboard_ перед _Template_, ведь для текстового сообщения дописываем _Message_.
Пример: было `mainMenuTemplate`, будет `mainMenuKeyboardTemplate`.

2020-11-29 07:48 UTC, paratskiy approved these changes

2020-11-29 17:35 UTC, GorgeousPuree approved these changes

2020-11-29 17:51 UTC, merged