Location handler
paratskiy-organization/neighbor_helper pull request #35
Opened 2020-12-06 00:01 UTC by maksim-luzin

Создание и обновление локации.
При нажатии на кнопку "Добавить локацию" происходит переход меню "Выбор локации".
После выбора локации происходит определение globalName и формирование клавиатуры localName из уже определённых локаций.
Возможно выбрать одно из существующих названий (обновить) или вписать своё (создать).
После этого локация будет обновлена, создана.

2020-12-06 18:36 UTC, GorgeousPuree requested changes
1. Директорию `aboutUsTemplate.js` переименовать в `aboutUsTemplate`
2. Необходимо добавить миграцию, которая выставляет дефолтное значение `state` как `{}`.
3. По возможности убрать сапресс правил eslint'а, а то их становится многовато. 

И сам пересмотри код ещё раз, вдруг, что-то заметишь.

2020-12-06 18:36 UTC, GorgeousPuree commented on src/features/index.js
> +  const result = await getOne({ telegramId: message.from.id }, 'state');
`const result = await getOne({ telegramId: message.from.id, params: ['state'] });`

2020-12-06 18:36 UTC, GorgeousPuree commented on src/templates/locationTemplates/addLocationMessageTemplate.js
> +const addLocationMenuMessageTemplate = 'Выберите локацию по карте\nили добавте текущую.';
'Выберите любую локацию, нажав на "Скрепку" -> "Локация" или просто отправьте текущую.'
Переходы на новые строки не нужны.

2020-12-06 18:36 UTC, GorgeousPuree commented on src/templates/locationTemplates/addLocationNameMessageTemplate.js
> +const addLocationNameMenuMessageTemplate = 'Выберите название локации\nиз списка\nили введите своё';
'Выберите локацию, которую хотите изменить или создайте новую, введя её имя.'

2020-12-06 23:07 UTC, maksim-luzin commented
Устранил замечания.
При команде '/start' выдаётся пустой state по умолчанию.
Если по какой-то причине state не удаётся загрузить то производится попытка записи, нахождения пользователя в БД.
Для пользователя  выдаётся ошибка "Ой что-то пошло не так".

2020-12-07 10:53 UTC, GorgeousPuree reviewed
А зачем ты делаешь throw, если !result.succeeded ? Лог можно прямо в этой проверке делать. В сервисах и так трай кетчи есть. Получается, на одну ошибку вылетит два throw, хотя одного достаточно. Я считаю, что нужно вернуть как было и добавить консол.логи в тело проверки на !result.succeeded

2020-12-07 12:25 UTC, maksim-luzin commented
Если результат не успешен то это перебрасует в feature/index.js. В нём происходит отправка сообщения и лог ошибки. При этом нет необходимости писать каждый раз лог ошибки. Для пользователя ничего не поменялось. Предлагаю сделать как рассудит самый опытный из нас всех - Богдан.

2020-12-07 12:47 UTC, GorgeousPuree commented
Лучше создать обёртку, которая вызывает консол.логи и ретурнит дефолтное сообщение и вызывать уже её в теле !result.succeeded, но точно не создавать ещё один try/catch.
Хорошо, ждём ответ Богдана.

> Если результат не успешен то это перебрасует в feature/index.js. В нём происходит отправка сообщения и лог ошибки. При этом нет необходимости писать каждый раз лог ошибки. Для пользователя ничего не поменялось. Предлагаю сделать как рассудит самый опытный из нас всех - Богдан.

2020-12-07 13:00 UTC, paratskiy commented
Я думаю, сделать как говорит Егор

2020-12-07 13:00 UTC, paratskiy approved these changes

2020-12-07 16:40 UTC, GorgeousPuree commented
Ладно, пусть уже так будет, мне с этой веткой работать надо.

2020-12-07 16:40 UTC, GorgeousPuree approved these changes

2020-12-07 16:40 UTC, merged