Add assignment
paratskiy-organization/neighbor_helper pull request #47
Opened 2020-12-13 00:17 UTC by maksim-luzin

2020-12-13 12:35 UTC, paratskiy approved these changes

2020-12-13 13:12 UTC, paratskiy requested changes
.

2020-12-13 13:16 UTC, GorgeousPuree commented on src/features/textHandler.js
> +        return response;
Эти категории в `textHandler`'е выносил я, чтобы потом перенаправлять в `categoryHandler`, где уже в зависимости от `flow.step` (либо `FIND_ASSIGNMENTS`, либо `ADD_ASSIGNMENTS`) возвращать соответствующий экшен. 
А тут появилась проверка на 61 строке `if (state.step === findAssignmentsFlowSteps.CHOOSE_CATEGORY)`, типа чтобы не ломать то, что есть, а вызов экшена добавления категории при создании объявления оказался в `stateDefaultHandler`, вместо того чтобы поместить его в `categoryHandler`.
Можно ведь было в одном стиле это написать: либо подстроиться под то, что есть, либо переписать в свой вариант, если мой не понравился. А так каша выходит, выбор категории для поиска и создания объявления написаны не в одном стиле.

2020-12-13 13:53 UTC, maksim-luzin commented on src/actions/addAssignmentAction.js
> +    : false;
Лично для меня так более наглядно. 
1. Условие
2. При выполнении условия.
3 При невыполнении условия.

2020-12-13 13:53 UTC, GorgeousPuree requested changes
Я хочу чтобы выбор категории, что для поиска, что для подачи объявления был написан в одном стиле (см. коммент). 
Проще всего перенести это из `defaultStateHandler` в `categoryHandler `
```
    case ADD_ASSIGNMENT.CHOOSE_CATEGORY:
      response = await chooseCategoryAssignmentAction(request, state);
      return response; 
```
И убрать проверку `if (state.step === findAssignmentsFlowSteps.CHOOSE_CATEGORY`) в `textHandler`.

Либо подогнать выбор категории объявления при поиске под то, как ты написал выбор категории объявления при создании.

2020-12-13 13:53 UTC, GorgeousPuree commented on src/helpers/locationNamesKeyboard/index.js
> +  console.log(result);
консол.логи надо убрать

2020-12-13 14:13 UTC, maksim-luzin commented on src/actions/mainActions.js
> +  ];
У меня и так всё давно вынесено. Но это исключение. Только при команде /start необходимо стирать одно входящее сообщение. Не вижу смысла для одного раза писать что-то отдельно. По коду видно - это ответ. Он не слишком большой.

2020-12-13 20:02 UTC, maksim-luzin reviewed
Кое-что переделал. 
Богдан твой deleteMessage не подходит. У меня нет объекта request.
Декораторы, используемые только в одном модуле, выносить в отдельный файл не вижу смысла.

2020-12-14 09:06 UTC, paratskiy commented on src/actions/addAssignmentAction.js
> +}
Это не важно, я считаю в Actions должны быть только экшены

2020-12-14 14:09 UTC, GorgeousPuree commented on src/features/textHandler.js
> +        return response;
> Это вынужденная мера. У меня проверяет название категорий по заданной клавиатуре выбора категорий. В этой части в принудительном порядке меняется message.text. После этого у меня весь код ломается.

Поэтому я и написал этот свитч для категорий, который меняет message.text: чтобы в экшены не попали какие-то левые категории. Просто если бы ты сразу глянул, что уже написано, то мог бы подстроиться под существующий код, а так у нас два непохожих друг на друга куска, которые делают почти то же самое.

2020-12-14 21:54 UTC, maksim-luzin commented on src/features/textHandler.js
> +        return response;
Посмотри ещё раз. textHandler.js переписал теперь это опять обычный switch с этой частью согласен.
Я и смотрел в существующий код, но твои вызовы:
1) textHandler -> categoryHandler -> findAssignmentsFlowSteps
2) stateDefaultHandler -> addFoundAssignmentCategoryAction
Считаю некорректными. Тем более нормального объяснения я так и не получил. Если ввёл categoryHandler используй его.
Не уверен в корректности переопределения значения поля стандартного запроса message.text ещё до использования action. На мой взгляд, если возникает необходимость - добавь переменную или своё уникальное поле.

2020-12-14 21:54 UTC, maksim-luzin commented on src/helpers/responseMessage/index.js
> +  ];
Богдан твой deleteMessage не подходит. У меня нет объекта request.

2020-12-14 22:04 UTC, GorgeousPuree commented on src/features/textHandler.js
> +        return response;
> 2\. Тем более нормального объяснения я так и не получил.

Да я же говорил на прошлом колле, что случайно в `stateDefaultHandler` добавил `addFoundAssignmentCategoryAction`, и он не нужен. Я в своей ветке, в которой сейчас работаю, уже убрал этот кейс оттуда.

> 2\. Не уверен в корректности переопределения значения поля стандартного запроса message.text ещё до использования action. На мой взгляд, если возникает необходимость - добавь переменную или своё уникальное поле.

Можно и так, даже, наверное, лучше. Главное, случайно не забрать `message.text` в качестве категории в экшене, т.к. там может быть категория на русском языке, а в бд всё на англ. Просто я таким образом обезопасил дальнейшее использование `message.text`.

2020-12-14 22:05 UTC, maksim-luzin commented on src/actions/addAssignmentAction.js
> +}
Ещё раз посмотри внимательно - это просто обёртка метода responseMessage, который находиться в Helpers.
Зачем обёртку метода, используемую в одном файле, выносить в отдельное место?

2020-12-16 10:11 UTC, paratskiy approved these changes

2020-12-16 10:22 UTC, GorgeousPuree approved these changes

2020-12-16 10:23 UTC, merged