Assignment actions
paratskiy-organization/neighbor_helper pull request #49
Opened 2020-12-13 01:50 UTC by paratskiy

Добавил возможность смены статуса и удаления объявлений. Заменил editMessageText на editMessageReplyMarkup, более подходящее. Вынес телеграм-методы в helpers/telegram и переписал экшены с использованием этих хелперов. Исправил баг(не большой) с добавлением/удалением объяв из избранных. Хз, может еще какие-то не большие изменения)

2020-12-13 02:49 UTC, GorgeousPuree commented
> Хз, может еще какие-то не большие изменения)

Интересно) Днём гляну.

2020-12-13 14:11 UTC, GorgeousPuree commented on src/services/assignment.service.js
> +          id: elem.Assignment.dataValues.id,
Когда я это писал, то айдишник изначально был:
https://github.com/paratskiy-organization/neighbor_helper/blob/b57049220a95f27e16a5c353978e5f079116eeb9/src/services/assignment.service.js#L148
А в пулл реквесте на пагинацию этот айдишник ты убрал случайно, а я не заметил.
https://github.com/paratskiy-organization/neighbor_helper/blob/dee87887db88d25ada2b25f363f0a4202e710ed6/src/services/assignment.service.js#L176
Хорошо, что увидел и исправил.

2020-12-13 14:25 UTC, GorgeousPuree requested changes
![favoritesBug](https://user-images.githubusercontent.com/46875481/102014563-47292b80-3d5f-11eb-8c42-e1df3ddc1f6e.gif)


Нажатие "Убрать из избранных" находясь в меню "Избранные" удаляет сообщение-объявление, но не удаляет сообщение-пагинацию, что влечёт за собой ошибки. 

Надо либо удалять сообщение-пагинацию тоже, указывая айдишник сообщения (больше на один чем предыдущий), либо не удалять сообщение-объявление, а изменять кнопку "Убрать из избранных" на "В избранные", как при поиске объявлений. 
Но я бы смотрел в сторону первого.

2020-12-14 08:59 UTC, maksim-luzin approved these changes

2020-12-16 10:01 UTC, GorgeousPuree approved these changes

2020-12-16 10:07 UTC, merged