Edit assignment.
paratskiy-organization/neighbor_helper pull request #61
Opened 2020-12-22 18:42 UTC by maksim-luzin

2020-12-22 23:34 UTC, paratskiy submitted a review, later dismissed

2020-12-23 00:06 UTC, GorgeousPuree commented
Макс, там новые конфликты появились, посмотри.

2020-12-23 00:07 UTC, GorgeousPuree commented on src/features/index.js
> +    // return messageDefaultAction();
Посмотри как в деве сейчас. Нам этот блок файналли вообще не нужен.

2020-12-23 00:30 UTC, GorgeousPuree requested changes
Необходимо зарезолвить конфликты и посмотреть комментарии.

2020-12-23 00:30 UTC, GorgeousPuree commented on src/features/textHandler.js
>        return mainMenuAction(request);
Если теперь тут нет авейта, то как же проверка будет срабатывать? В респонсе будет просто промис. С этим надо что-то сделать

2020-12-23 01:26 UTC, GorgeousPuree requested changes

2020-12-23 01:26 UTC, GorgeousPuree commented on src/actions/addAssignmentAction.js
> +  const transaction = await sequelize.transaction();
Используй инстанс сиквалайза с '../database'.models.sequelize, как во всех сервисах.
Если добавил транзакцию, то почему оставил строчки 231-233? Их нужно убрать. Когда уберешь, заметишь, что объявления перестанут создаваться, потому что транзакция не работает. Если бы работала, и если бы произошел эксепшн, то нигде в логах этого не было бы, ведь в кетче просто идёт роллбэк, а на верхний уровень, где написан консол.лог, ничего не попадает.
Пожалуйста, пересмотри код этого метода внимательно и отладь.

2020-12-23 09:51 UTC, maksim-luzin commented
Разрешил конфликты слияния. Убрал transactions из создания и редактирования объявления.

2020-12-23 10:06 UTC, GorgeousPuree commented on src/features/textHandler.js
>        return mainMenuAction(request);
@maksim-luzin , этот момент не решён.

2020-12-23 10:43 UTC, GorgeousPuree requested changes
Надо исправить моменты, которые я указал. Прогоняй код еслинтом перед пушем. 
`assignment.service` весь красный, видимо, где-то скобок не хватает.

2020-12-23 10:43 UTC, GorgeousPuree commented on src/features/index.js
>  };
Тут не хватает ещё одной фигурной скобки.

2020-12-23 10:43 UTC, GorgeousPuree commented on src/actions/editAssignmentAction.js
> +  await setState(message.from.id, null, null, null, transaction);
Не убрал `transaction`.

2020-12-23 12:12 UTC, GorgeousPuree approved these changes

2020-12-23 12:43 UTC, paratskiy approved these changes

2020-12-23 12:43 UTC, merged