Add location in add and edit assignment
paratskiy-organization/neighbor_helper pull request #63
Opened 2020-12-23 23:05 UTC by maksim-luzin

2020-12-23 23:49 UTC, GorgeousPuree requested changes
Во время добавления новой локации при создании объявления необходимо ввести новое или выбрать существующее имя локации. На клавиатуре есть кнопки с названием локаций, а также кнопка "Добавить локацию". При её нажатии возникает исключение.
![locationBug](https://user-images.githubusercontent.com/46875481/103044678-18465d00-458a-11eb-9bbc-e578d356e901.gif)

2020-12-24 20:08 UTC, GorgeousPuree requested changes

2020-12-24 20:25 UTC, paratskiy approved these changes

2020-12-24 21:54 UTC, maksim-luzin commented on src/features/index.js
> +      console.log(state);
Полностью согласен. Убрал.

2020-12-25 01:14 UTC, GorgeousPuree approved these changes
Пожалуйста, прогоняй еслинтом перед пушем.

2020-12-25 12:53 UTC, merged