Resolving updateLocation TODO.
paratskiy-organization/neighbor_helper pull request #66
Opened 2020-12-27 16:48 UTC by GorgeousPuree

2020-12-27 20:07 UTC, paratskiy approved these changes

2020-12-27 22:27 UTC, maksim-luzin requested changes
Думаю locationAction.js нужно вернуть всё назад. Ведь объект уже сформирован.

2020-12-27 22:27 UTC, maksim-luzin commented on src/actions/locationAction.js
> -    ...state.data,
Не уверен, что это хорошая идея.

2020-12-28 00:22 UTC, GorgeousPuree commented on src/actions/locationAction.js
> -    ...state.data,
Вернул как было.

2020-12-28 05:50 UTC, maksim-luzin approved these changes

2020-12-28 10:35 UTC, merged